config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: { 
    registrations: "suppliers/registrations",
    sessions: "suppliers/sessions"
   }
  devise_for :offtakers, controllers: { 
    registrations: "offtakers/registrations",
    sessions: "offtakers/sessions"
   }
   devise_for :admins, controllers: { 
    registrations: "admin/registrations",
    sessions: "admin/sessions"
   }, path: 'admin'

  authenticate :admin, ->(admin) { admin } do
    namespace :admin do
      get '/', to: 'supplier_locations#index'
      post '/supplier_locations/:id/verify', as: :verify, to: "supplier_locations#verify"
    end
  end

  namespace :api do
    namespace :v1 do
      # Offtaker location creation
      get '/charts/offtaker_location_weekly', 
      to: 'charts#offtaker_location_weekly', 
      as: 'charts_offtaker_location_weekly'

      get '/charts/offtaker_location_monthly', 
      to: 'charts#offtaker_location_monthly', 
      as: 'charts_offtaker_location_monthly'

      get '/charts/offtaker_location_yearly', 
      to: 'charts#offtaker_location_yearly', 
      as: 'charts_offtaker_location_yearly'  

      # Offtaker location by volume requested
      get '/charts/offtaker_location_volume_weekly', 
      to: 'charts#offtaker_location_volume_weekly', 
      as: 'charts_offtaker_location_volume_weekly'

      get '/charts/offtaker_location_volume_monthly', 
      to: 'charts#offtaker_location_volume_monthly', 
      as: 'charts_offtaker_location_volume_monthly'

      get '/charts/offtaker_location_volume_yearly', 
      to: 'charts#offtaker_location_volume_yearly', 
      as: 'charts_offtaker_location_volume_yearly'  

      # Offtaker location by oxygen_interest requested
      get '/charts/offtaker_location_oxygen_interest_weekly', 
      to: 'charts#offtaker_location_oxygen_interest_weekly', 
      as: 'charts_offtaker_location_oxygen_interest_weekly'

      get '/charts/offtaker_location_oxygen_interest_monthly', 
      to: 'charts#offtaker_location_oxygen_interest_monthly', 
      as: 'charts_offtaker_location_oxygen_interest_monthly'

      get '/charts/offtaker_location_oxygen_interest_yearly', 
      to: 'charts#offtaker_location_oxygen_interest_yearly', 
      as: 'charts_offtaker_location_oxygen_interest_yearly'  

      # Scenario creation
      get '/charts/scenario_weekly', 
      to: 'charts#scenario_weekly', 
      as: 'charts_scenario_weekly'

      get '/charts/scenario_monthly', 
      to: 'charts#scenario_monthly', 
      as: 'charts_scenario_monthly'

      get '/charts/scenario_yearly', 
      to: 'charts#scenario_yearly', 
      as: 'charts_scenario_yearly'  

      # Average road costs
      get '/charts/average_road_costs_weekly', 
      to: 'charts#average_road_costs_weekly', 
      as: 'charts_average_road_costs_weekly'

      get '/charts/average_road_costs_monthly', 
      to: 'charts#average_road_costs_monthly', 
      as: 'charts_average_road_costs_monthly'

      get '/charts/average_road_costs_yearly', 
      to: 'charts#average_road_costs_yearly', 
      as: 'charts_average_road_costs_yearly'  

      # Average distance
      get '/charts/average_distance_weekly', 
      to: 'charts#average_distance_weekly', 
      as: 'charts_average_distance_weekly'

      get '/charts/average_distance_monthly', 
      to: 'charts#average_distance_monthly', 
      as: 'charts_average_distance_monthly'

      get '/charts/average_distance_yearly', 
      to: 'charts#average_distance_yearly', 
      as: 'charts_average_distance_yearly'  

      # Average pipeline costs
      get '/charts/average_pipeline_costs_weekly', 
      to: 'charts#average_pipeline_costs_weekly', 
      as: 'charts_average_pipeline_costs_weekly'

      get '/charts/average_pipeline_costs_monthly', 
      to: 'charts#average_pipeline_costs_monthly', 
      as: 'charts_average_pipeline_costs_monthly'

      get '/charts/average_pipeline_costs_yearly', 
      to: 'charts#average_pipeline_costs_yearly', 
      as: 'charts_average_pipeline_costs_yearly'  

      # Offtaker creation
      get '/charts/offtaker_weekly', 
      to: 'charts#offtaker_weekly', 
      as: 'charts_offtaker_weekly'

      get '/charts/offtaker_monthly', 
      to: 'charts#offtaker_monthly', 
      as: 'charts_offtaker_monthly'

      get '/charts/offtaker_yearly', 
      to: 'charts#offtaker_yearly', 
      as: 'charts_offtaker_yearly'  

      # Offtaker scenarios created
      get '/charts/offtaker_scenarios_created_weekly', 
      to: 'charts#offtaker_scenarios_created_weekly', 
      as: 'charts_offtaker_scenarios_created_weekly'

      get '/charts/offtaker_scenarios_created_monthly', 
      to: 'charts#offtaker_scenarios_created_monthly', 
      as: 'charts_offtaker_scenarios_created_monthly'

      get '/charts/offtaker_scenarios_created_yearly', 
      to: 'charts#offtaker_scenarios_created_yearly', 
      as: 'charts_offtaker_scenarios_created_yearly'  
    end
  end

  resources :scenarios, only: [:create, :show, :destroy]
  post '/scenarios/:id/mark-favourite', as: :mark_favourite, to: "scenarios#mark_favourite"
  post '/scenarios/:id/calculate-again', as: :calculate_again, to: "scenarios#calculate_again"


  namespace :suppliers, suppliers: true do 
    get '/', to: 'supplier_locations#dashboard'
    get '/filter', to: 'supplier_locations#filter', as: :filter
    resources :supplier_locations, except: [:index]
  end

  namespace :offtakers, offtakers: true do 
    get '/', to: 'offtaker_locations#dashboard'
    resources :offtaker_locations, except: [:index]
  end

  root 'pages#home'
  get '/about', to: "pages#about"
  get '/terms_and_conditions', to: "pages#terms_and_conditions"
  get '/privacy_statement', to: "pages#privacy_statement"

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :supplier_locations
  has_many :scenarios, through: :supplier_locations

  
end

app/models/supplier_location.rb
class SupplierLocation < ApplicationRecord
  include Hashid::Rails

  belongs_to :supplier
  has_many :scenarios
  has_many :supply_types, inverse_of: :supplier_location
  accepts_nested_attributes_for :supply_types, reject_if: :all_blank, allow_destroy: true
  geocoded_by :coordinates

  after_save :set_prefixed_id
  after_save :update_scenarios

  validates :name, presence: true

  def coordinates
    [self.latitude, self.longitude]
  end

  def address
    if self.house_nr && self.postal_code
      "#{self.house_nr}#{"- #{self.postal_code}" unless self.postal_code.blank?}"
    else
      ""
    end
  end

  def set_prefixed_id
    if self.prefixed_id.nil?
      self.prefixed_id = "s_#{self.id}"
      self.save
    end
  end

  def update_scenarios
    self.scenarios.each do |scenario|
      scenario.run_calculations
      scenario.save
    end
  end

end

app/controllers/admin/supplier_locations_controller.rb
class Admin::SupplierLocationsController < Admin::BaseController
  def index
    @dashboard = true
    if params[:supply_type]
      supply_filter_types = params.require(:supply_type).permit(['Standard', 'ITMs', 'Pure', 'High pure', 'Ultrapure'].map {|item| item.to_sym}).to_hash.map {|key, value| key }
    else
      supply_filter_types = []
    end
    if params[:request_type]
      @request_filter_types = params.require(:request_type).permit(['Standard', 'ITMs', 'Pure', 'High pure', 'Ultrapure'].map {|item| item.to_sym}).to_hash.map {|key, value| key }
    else
      @request_filter_types = []
    end
    if params[:q]
      @supplier_locations = SupplierLocation.where("name ILIKE ?", "%#{params[:q]}%").order('updated_at DESC')

    else
      @supplier_locations = SupplierLocation.all.order('updated_at DESC')
    end
    if supply_filter_types.any?
      @supplier_locations = @supplier_locations.joins(:supply_types).where(supply_types: { name: supply_filter_types })
    end
    @supplier_locations = @supplier_locations.paginate(page: params[:page], per_page: 5)
    set_metrics_data
    respond_to do |format|
      format.html
      format.json {
          render json: {
              locations: render_to_string(partial: "admin/supplier_locations/locations", formats: [:html]), 
          }
      }
    end
  end

  def verify
    @supplier_location = SupplierLocation.find(params[:id])
    @supplier_location.verified = !@supplier_location.verified
    @supplier_location.save
    respond_to do |format|
      format.js
      format.json {
        render json: {
            supplier_location: @supplier_location,
        }
    }
    end
  end

  private

  def set_metrics_data
    @top_five_offtaker_location_by_volume_required = OfftakerLocation.all.order(required_hydrogen_volume: :desc).first(5)
    @top_five_supplier_location_by_scenarios = SupplierLocation.joins(:scenarios).group(:name).count.sort.first(5)
  end
end

app/controllers/suppliers/base_controller.rb
class Suppliers::BaseController < ApplicationController
  before_action :authenticate_supplier!
end

app/controllers/suppliers/registrations_controller.rb
class Suppliers::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_offtakers_offtaker_location_path
  end
  
end

app/controllers/suppliers/sessions_controller.rb
class Suppliers::SessionsController < Devise::SessionsController
  protected
  
  def after_sign_in_path_for(resource)
    suppliers_path
  end

end

app/controllers/suppliers/supplier_locations_controller.rb
class Suppliers::SupplierLocationsController < Suppliers::BaseController
  before_action :set_supplier_location, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_supplier!, if: :current_admin, only: [:show]
  skip_before_action :authenticate_supplier!, only: [:filter]

  def dashboard
    @dashboard = true
    if params[:q]
      @supplier_locations = current_supplier.supplier_locations.where("name ILIKE ?", "%#{params[:q]}%").order('updated_at DESC').paginate(page: params[:page], per_page: 5)
    else
      @supplier_locations = current_supplier.supplier_locations.order('updated_at DESC').paginate(page: params[:page], per_page: 5)
    end
    @scenarios = current_supplier.scenarios
    respond_to do |format|
      format.html
      format.json {
          render json: {
              locations: render_to_string(partial: "suppliers/supplier_locations/locations", formats: [:html]), 
          }
      }
    end
  end

  def filter
    @supplier_locations_count = SupplierLocation.near(
      [params[:latitude].to_f, params[:longitude].to_f], 
      500, 
      units: :km
    ).joins(:supply_types).where(
      'supply_types.minimum_hydrogen_volume <= ? AND supply_types.maximum_hydrogen_volume >= ? AND supply_types.pressure_type_hydrogen = ? AND supply_types.name = ?',
      params[:volume].to_f,
      params[:volume].to_f,
      params[:pressure].to_f,
      params[:purity]
    ).where(
      verified: true,
      available: true,
    ).length
    respond_to do |format|
      format.json {
          render json: {
              supplier_locations_count: @supplier_locations_count
          }
      }
    end
  end

  def show
    @offtaker_locations = OfftakerLocation.near(@supplier_location.coordinates, 200, units: :km)
  end

  def new
    @supplier_location = SupplierLocation.new
    @supplier_location.supply_types.build
  end

  def create
    @supplier_location = SupplierLocation.new(supplier_location_params)
    @supplier_location.verified = true
    @supplier_location.supplier = current_supplier
    if @supplier_location.save!
      redirect_to suppliers_supplier_location_path(@supplier_location)
    else
      render :new
    end
  end

  def edit
    @supplier_location.supply_types.build
  end

  def update
    if @supplier_location.update!(supplier_location_params)
      redirect_to suppliers_supplier_location_path(@supplier_location)
    else
      render :edit
    end
  end

  def destroy
    if @supplier_location.destroy
      redirect_to suppliers_path
    else
      redirect_to suppliers_path
    end
  end

  private

  def set_supplier_location
    @supplier_location = SupplierLocation.find(params[:id])
  end

  def supplier_location_params
    params.require(:supplier_location).permit(
      :name, 
      :longitude, 
      :latitude, 
      :postal_code, 
      :house_nr, 
      :verified,
      :available,
      :pickup_available,
      :has_drtfc,
      :purification_onsite,
      supply_types_attributes: [
        :id,
        :verified,
        :available,
        :pickup_available,
        :has_drtfc,
        :purification_onsite,
        :name,
        :minimum_hydrogen_volume,
        :maximum_hydrogen_volume,
        :pressure_type_hydrogen,
        :compression_costs,
        :transport_costs,
        :purity_proof,
        :supply_proof
      ]
    )
  end
end

app/views/suppliers/supplier_locations/_location.html.erb
<li class="location-list-item">
    <%= link_to suppliers_supplier_location_path(supplier_location), class: "location-list-data" do %>
      <h2>
        <%= supplier_location.name %>
      </h2>
      <p>
        <%= supplier_location.address %>
      </p>
    <% end %>
    <div class="location-list-actions">
      <%= link_to suppliers_supplier_location_path(supplier_location), class: "btn btn-primary" do %>
        <i class="fa-solid fa-eye"></i>
      <% end %>
      <%= link_to suppliers_supplier_location_path(supplier_location), method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this location?" }, class: "btn btn-danger" do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
      <%= link_to edit_suppliers_supplier_location_path(supplier_location), class: "btn btn-warning" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
    </div>
</li>

app/views/suppliers/supplier_locations/_locations.html.erb
  <% @supplier_locations.each do |supplier_location| %>
    <%= render partial: "location", locals: { supplier_location: supplier_location } %>
  <% end %>
<%= will_paginate @supplier_locations %>

<% unless @supplier_locations.any? %>
  <p>
    No locations
  </p>
<% end %>

app/views/suppliers/supplier_locations/_supplier_location_details.html.erb
<div class="data">
  <div class="data-label">
    Name
  </div>
  <div class="data-value">
    <%= supplier_location.name %>
  </div>
  <div class="data-label">
    Longitude
  </div>
  <div class="data-value">
    <%= supplier_location.longitude %>
  </div>
  <div class="data-label">
    Latitude
  </div>
  <div class="data-value">
    <%= supplier_location.latitude %>
  </div>
  <div class="data-label">
    Postal code
  </div>
  <div class="data-value">
    <%= supplier_location.postal_code %>
  </div>
  <div class="data-label">
    House number
  </div>
  <div class="data-value">
    <%= supplier_location.house_nr %>
  </div>
  <div class="data-label">
    Can off-takers use their own transport to pickup at this location?
  </div>
  <div class="data-value">
    <%= supplier_location.pickup_available ? 'Yes' : 'No' %>
  </div>
</div>

app/views/suppliers/supplier_locations/_supply_type_details.html.erb
  <div class="data">
    <div class="data-label">
      Name 
    </div>
    <div class="data-value">
      <%= supply_type.name %> 
      <span data-balloon-pos="up" aria-label="<%= supply_type.present.description %>">
        <i class="fa-solid fa-circle-question"></i>
      </span>
    </div>
    <div class="data-label">
      Minimum hydrogen volume
    </div>
    <div class="data-value">
      <%= supply_type.minimum_hydrogen_volume %> kg 
      <span class="text-secondary data-unit">/ day</span>
    </div>
    <div class="data-label">
      Maximum hydrogen volume
    </div>
    <div class="data-value">
      <%= supply_type.maximum_hydrogen_volume %> kg 
      <span class="text-secondary data-unit">/ day</span>
    </div>
    <div class="data-label">
      Pressure type hydrogen
    </div>
    <div class="data-value">
      <%= supply_type.pressure_type_hydrogen %> bar
    </div>
    <div class="data-label">
      Compression costs
    </div>
    <div class="data-value">
      <%= supply_type.present.compression_costs %> 
      <span class="text-secondary data-unit">/ kg</span>
    </div>
    <div class="data-label">
      Transport costs
    </div>
    <div class="data-value">
      <%= supply_type.present.transport_costs %>
      <span class="text-secondary data-unit">/ km</span>
    </div>
    <div class="data-label">
      Proof of purity
    </div>
    <div class="data-value">
      <% if supply_type.purity_proof.attached? %>
        <%= link_to "Open file", cloudinary_url(supply_type.purity_proof.key), target: "_blank" %>
      <% else %>
        Not provided
      <% end %>
    </div>
    <div class="data-label">
      Proof of supply
    </div>
    <div class="data-value">
      <% if supply_type.supply_proof.attached? %>
        <%= link_to "Open file", cloudinary_url(supply_type.supply_proof.key), target: "_blank" %>
      <% else %>
        Not provided
      <% end %>
    </div>
  </div>

app/views/suppliers/supplier_locations/dashboard.html.erb
<% content_for :title, "Dashboard for supplier" %>

<div class="dashboard-wrapper">
  <div class="dashboard-container">
    <div class="sidebar">
      <%= link_to root_path do %>
        <%= render partial: 'shared/logo' %>
      <% end %>
      <ul class="list-unstyled">
        <li>
          <%= link_to "#locations" do %>
            <i class="fa-solid fa-location-dot"></i> Locations
          <% end %>
        </li>
        <li>
          <%= link_to "#scenarios" do %>
            <i class="fa-solid fa-route"></i> Scenarios
          <% end %>
        </li>
      </ul>
    </div>
    <div class="dashboard">
      <div class="container position-relative pt-4">
      <%= render partial: "shared/dropdown" %>
        <div class="row">
          <div class="col-12">
            <h1 class="mt-3">
              Supplier dashboard
            </h1>
            <section id="locations" class="py-2">
              <h2 class="mt-3">
                My locations
              </h2>
              <div class="location-list-wrapper" data-controller="search">
                <div class="field">
                  <input 
                    type="text" 
                    data-search-target="input" 
                    data-action="input->search#handleInput" 
                    data-url="<%= suppliers_url %>"
                    class="form-control sized-input"
                    placeholder="Search"
                  >
                </div>
                <ul class="list-unstyled location-list" data-search-target="list">
                  <%= render partial: "locations", locals: { supplier_locations: @supplier_locations } %>
                </ul>

                <%= link_to new_suppliers_supplier_location_path, class: "btn btn-primary" do %>
                  Add new location <i class="fa-solid fa-plus"></i>
                <% end %>
            </section>
            <section id="scenarios" class="py-2">
              <h2>
                Scenarios
              </h2>
              <ul class="list-unstyled">
                <% @scenarios.order('created_at DESC').each do |scenario| %>
                  <li id="<%= dom_id scenario %>">
                    <%= scenario.created_at.strftime('%e %b %Y %H:%M%p') %>
                    <div class="button-wrapper">
                      <button data-controller="mark-favourite" data-action="click->mark-favourite#handleClick"
                      data-url="<%= mark_favourite_url(scenario) %>"
                      class="rating <%= 'active' if scenario.favourite %>">
                        <i class="fa-solid fa-star"></i> 
                      </button>
                      <%= link_to scenario_path(scenario) do %>
                        <%= scenario.offtaker_location.name %> &rarr; <%= scenario.supplier_location.name %> - <%= scenario.distance %>km
                      <% end %>
                    </div>
                      <a href="mailto:<%= offtaker_signed_in? ? scenario.supplier_location.supplier.email : scenario.offtaker_location.offtaker.email %>?subject=Contact via H2near.me" target="_blank">
                        <%= offtaker_signed_in? ? scenario.supplier_location.supplier.email : scenario.offtaker_location.offtaker.email %>
                      </a>
                  </li>
                <% end %>
              </ul>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/suppliers/supplier_locations/edit.html.erb
<% content_for :title, "Edit supplier location #{@supplier_location.name}" %>

<div class="container" data-controller="geocoder" data-key="<%= ENV['MAPBOX_API_KEY'] %>">
  <div class="row">
    <div class="col-12 col-md-6 pb-4 order-2 order-md-1">
      <div class="form-wrapper">
        <div class="form">
          <%= link_to suppliers_supplier_location_path(@supplier_location), class: "back-button" do %>
            &larr; Back to detail page
          <% end %>
          <h1>
            Edit supplier location '<%= @supplier_location.name %>'
          </h1>
          <%= render partial: "form", locals: { supplier_location: @supplier_location } %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 order-1 order-md-2">
      <div id="map" data-geocoder-target="map"></div>
      <div class="map-padding"></div>
    </div>
  </div>
</div>

app/views/suppliers/supplier_locations/new.html.erb
<% content_for :title, "New supplier location" %>

<div class="container" data-controller="geocoder" data-key="<%= ENV['MAPBOX_API_KEY'] %>">
  <div class="row">
    <div class="col-12 col-md-6 pb-4 order-2 order-md-1">
      <div class="form-wrapper">
        <div class="form">
          <%= link_to suppliers_path, class: "back-button" do %>
            &larr; Back to dashboard
          <% end %>
          <h1>
            New supplier location
          </h1>
          <%= render partial: "form", locals: { supplier_location: @supplier_location } %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 order-1 order-md-2">
      <div id="map" data-geocoder-target="map"></div>
      <div class="map-padding"></div>
    </div>
  </div>
</div>

app/views/suppliers/supplier_locations/show.html.erb
<% content_for :title, "Location details for #{@supplier_location.name}" %>

<div class="container" data-controller="maps">
  <div class="row">
    <div class="col-12">
      <div>
        <div id="routing-results"></div>

        <div id="map" class="full-width" data-maps-target="map" data-routing="true" data-key="<%= ENV['MAPBOX_API_KEY'] %>" data-center="<%= [@supplier_location.longitude, @supplier_location.latitude].to_json %>" data-zoom="9" data-origin-location-id="<%= @supplier_location.id %>" data-locations="<%= @offtaker_locations.map {|offtaker_location| [offtaker_location.longitude, offtaker_location.latitude, (offtaker_location.name || offtaker_location.address), offtaker_location.id] }.to_json %>"></div>
        <div class="map-padding"></div>

      </div>
    </div>
    <div class="col-12 position-relative">
      <%= link_to (supplier_signed_in? ? suppliers_path : admin_path), class: "back-button" do %>
        &larr; Back to dashboard
      <% end %>
      <div class="under-map-button">
        <% if @offtaker_locations.any? && supplier_signed_in? %>
          <button class="btn btn-primary" data-location="<%= [@offtaker_locations.first.longitude, @offtaker_locations.first.latitude, (@offtaker_locations.first.name || @offtaker_locations.first.address), @offtaker_locations.first.id].to_json %>" data-action="click->maps#drawRoute">
            <span class="text-light">
              Find nearest location 
            </span>
            <i class="fa-solid fa-location-crosshairs"></i>
          </button>
        <% elsif admin_signed_in? %>
          <button data-controller="mark-verified" data-action="click->mark-verified#handleClick"
          data-url="<%= admin_verify_url(@supplier_location) %>"
          aria-label="<%= @supplier_location.verified ? 'This location is verified' : 'This location is not verified' %>"
          data-balloon-pos="left"
          class="btn <%=  @supplier_location.verified ? 'btn-success active' : 'btn-warning' %>">
            <i class="fa-solid fa-check"></i> 
          </button>
        <% end %>
      </div>
      <h1 class="mt-4">
        Location details for <%= @supplier_location.name %>
      </h1>
      <% if supplier_signed_in? %>
        <div class="buttons my-3">
          <%= link_to edit_suppliers_supplier_location_path(@supplier_location), class: "btn btn-warning" do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>      
          <%= link_to suppliers_supplier_location_path(@supplier_location), method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this location?" }, class: "btn btn-danger"  do %>
          <i class="fa-solid fa-trash-can"></i>
        <% end %>
        </div>
      <% end %>

      <ul class="nav nav-pills" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="details-tab" data-bs-toggle="tab" data-bs-target="#details" type="button" role="tab" aria-controls="details" aria-selected="true">
            Details
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="locations-tab" data-bs-toggle="tab" data-bs-target="#locations" type="button" role="tab" aria-controls="locations" aria-selected="false">
            Locations
          </button>
        </li>
      </ul>

      <div class="tab-content pb-4" id="myTabContent">
        <div class="tab-pane show active pb-4" id="details" role="tabpanel" aria-labelledby="details-tab">
          <div class="data-two-columns">
            <div class="data-wrapper">
              <h2 class="mb-3">
                Location details
              </h2>
              <%= render partial: "suppliers/supplier_locations/supplier_location_details", locals: { supplier_location: @supplier_location } %>
            </div>
            <div class="accordion mb-3" id="supply-types-accordion">
              <h2 class="mb-3">
                Supply details by purity
              </h2>
              <% @supplier_location.supply_types.each_with_index do |supply_type, index| %>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="<%= supply_type.id %>">
                    <button class="accordion-button <%= 'collapsed' unless index.zero? %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= supply_type.id %>" aria-expanded="true" aria-controls="collapse-<%= supply_type.id %>">
                      <%= supply_type.name %>
                    </button>
                  </h2>
                  <div id="collapse-<%= supply_type.id %>" class="accordion-collapse collapse <%= 'show' if index.zero? %>" aria-labelledby="<%= supply_type.id %>" data-bs-parent="#supply-types-accordion">
                    <div class="accordion-body light-wrapper pb-5">
                      <%= render partial: "suppliers/supplier_locations/supply_type_details", locals: { supply_type: supply_type } %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="tab-pane pb-4" id="locations" role="tabpanel" aria-labelledby="locations-tab">
          <ul class="list-unstyled" id="scenarios">
            <% if @supplier_location.scenarios.any? %>
              <%= render partial: "scenarios/scenario", collection: @supplier_location.scenarios %>
            <% else %>
              Nothing here yet
              <% if @offtaker_locations.any? && supplier_signed_in? %>
              , <a href="#" data-location="<%= [@offtaker_locations.first.longitude, @offtaker_locations.first.latitude, (@offtaker_locations.first.name || @offtaker_locations.first.address), @offtaker_locations.first.id].to_json %>" data-action="click->maps#drawRoute">Plot a route</a>
              <% else %>
                <div class="alert alert-info mt-3" role="alert">
                  Unfortunately there are no supplier locations available for your requirements.
                </div>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>