config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: { 
    registrations: "suppliers/registrations",
    sessions: "suppliers/sessions"
   }
  devise_for :offtakers, controllers: { 
    registrations: "offtakers/registrations",
    sessions: "offtakers/sessions"
   }
   devise_for :admins, controllers: { 
    registrations: "admin/registrations",
    sessions: "admin/sessions"
   }, path: 'admin'

  authenticate :admin, ->(admin) { admin } do
    namespace :admin do
      get '/', to: 'supplier_locations#index'
      post '/supplier_locations/:id/verify', as: :verify, to: "supplier_locations#verify"
    end
  end

  namespace :api do
    namespace :v1 do
      # Offtaker location creation
      get '/charts/offtaker_location_weekly', 
      to: 'charts#offtaker_location_weekly', 
      as: 'charts_offtaker_location_weekly'

      get '/charts/offtaker_location_monthly', 
      to: 'charts#offtaker_location_monthly', 
      as: 'charts_offtaker_location_monthly'

      get '/charts/offtaker_location_yearly', 
      to: 'charts#offtaker_location_yearly', 
      as: 'charts_offtaker_location_yearly'  

      # Offtaker location by volume requested
      get '/charts/offtaker_location_volume_weekly', 
      to: 'charts#offtaker_location_volume_weekly', 
      as: 'charts_offtaker_location_volume_weekly'

      get '/charts/offtaker_location_volume_monthly', 
      to: 'charts#offtaker_location_volume_monthly', 
      as: 'charts_offtaker_location_volume_monthly'

      get '/charts/offtaker_location_volume_yearly', 
      to: 'charts#offtaker_location_volume_yearly', 
      as: 'charts_offtaker_location_volume_yearly'  

      # Offtaker location by oxygen_interest requested
      get '/charts/offtaker_location_oxygen_interest_weekly', 
      to: 'charts#offtaker_location_oxygen_interest_weekly', 
      as: 'charts_offtaker_location_oxygen_interest_weekly'

      get '/charts/offtaker_location_oxygen_interest_monthly', 
      to: 'charts#offtaker_location_oxygen_interest_monthly', 
      as: 'charts_offtaker_location_oxygen_interest_monthly'

      get '/charts/offtaker_location_oxygen_interest_yearly', 
      to: 'charts#offtaker_location_oxygen_interest_yearly', 
      as: 'charts_offtaker_location_oxygen_interest_yearly'  

      # Scenario creation
      get '/charts/scenario_weekly', 
      to: 'charts#scenario_weekly', 
      as: 'charts_scenario_weekly'

      get '/charts/scenario_monthly', 
      to: 'charts#scenario_monthly', 
      as: 'charts_scenario_monthly'

      get '/charts/scenario_yearly', 
      to: 'charts#scenario_yearly', 
      as: 'charts_scenario_yearly'  

      # Average road costs
      get '/charts/average_road_costs_weekly', 
      to: 'charts#average_road_costs_weekly', 
      as: 'charts_average_road_costs_weekly'

      get '/charts/average_road_costs_monthly', 
      to: 'charts#average_road_costs_monthly', 
      as: 'charts_average_road_costs_monthly'

      get '/charts/average_road_costs_yearly', 
      to: 'charts#average_road_costs_yearly', 
      as: 'charts_average_road_costs_yearly'  

      # Average distance
      get '/charts/average_distance_weekly', 
      to: 'charts#average_distance_weekly', 
      as: 'charts_average_distance_weekly'

      get '/charts/average_distance_monthly', 
      to: 'charts#average_distance_monthly', 
      as: 'charts_average_distance_monthly'

      get '/charts/average_distance_yearly', 
      to: 'charts#average_distance_yearly', 
      as: 'charts_average_distance_yearly'  

      # Average pipeline costs
      get '/charts/average_pipeline_costs_weekly', 
      to: 'charts#average_pipeline_costs_weekly', 
      as: 'charts_average_pipeline_costs_weekly'

      get '/charts/average_pipeline_costs_monthly', 
      to: 'charts#average_pipeline_costs_monthly', 
      as: 'charts_average_pipeline_costs_monthly'

      get '/charts/average_pipeline_costs_yearly', 
      to: 'charts#average_pipeline_costs_yearly', 
      as: 'charts_average_pipeline_costs_yearly'  

      # Offtaker creation
      get '/charts/offtaker_weekly', 
      to: 'charts#offtaker_weekly', 
      as: 'charts_offtaker_weekly'

      get '/charts/offtaker_monthly', 
      to: 'charts#offtaker_monthly', 
      as: 'charts_offtaker_monthly'

      get '/charts/offtaker_yearly', 
      to: 'charts#offtaker_yearly', 
      as: 'charts_offtaker_yearly'  

      # Offtaker scenarios created
      get '/charts/offtaker_scenarios_created_weekly', 
      to: 'charts#offtaker_scenarios_created_weekly', 
      as: 'charts_offtaker_scenarios_created_weekly'

      get '/charts/offtaker_scenarios_created_monthly', 
      to: 'charts#offtaker_scenarios_created_monthly', 
      as: 'charts_offtaker_scenarios_created_monthly'

      get '/charts/offtaker_scenarios_created_yearly', 
      to: 'charts#offtaker_scenarios_created_yearly', 
      as: 'charts_offtaker_scenarios_created_yearly'  
    end
  end

  resources :scenarios, only: [:create, :show, :destroy]
  post '/scenarios/:id/mark-favourite', as: :mark_favourite, to: "scenarios#mark_favourite"
  post '/scenarios/:id/calculate-again', as: :calculate_again, to: "scenarios#calculate_again"


  namespace :suppliers, suppliers: true do 
    get '/', to: 'supplier_locations#dashboard'
    get '/filter', to: 'supplier_locations#filter', as: :filter
    resources :supplier_locations, except: [:index]
  end

  namespace :offtakers, offtakers: true do 
    get '/', to: 'offtaker_locations#dashboard'
    resources :offtaker_locations, except: [:index]
  end

  root 'pages#home'
  get '/about', to: "pages#about"
  get '/terms_and_conditions', to: "pages#terms_and_conditions"
  get '/privacy_statement', to: "pages#privacy_statement"

end

app/views/shared/_dropdown.html.erb
  <% if offtaker_signed_in? || supplier_signed_in? || admin_signed_in? %>
    <div class="bubble-dropdown-wrapper" data-controller="dropdown">
      <button data-action="click->dropdown#handleExpand">
        <span>
          <%= current_offtaker&.email || current_supplier&.email || current_admin&.email %> 
        </span>
        <i class="fas fa-caret-square-down"></i>
      </button>
      <div class="bubble-dropdown collapsed" data-target="dropdown.menu">
        <ul>
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <% if offtaker_signed_in? %>
              <%= link_to "Dashboard", offtakers_path %>
            <% elsif supplier_signed_in? %>
              <%= link_to "Dashboard", suppliers_path %>
            <% elsif admin_signed_in? %>
              <%= link_to "Dashboard", admin_path %>
            <% end %>
          </li>
          <% if offtaker_signed_in? %>
            <li>
              <%= link_to "Account", edit_offtaker_registration_path %>
            </li>
          <% elsif supplier_signed_in? %>
            <li>
              <%= link_to "Account", edit_supplier_registration_path %>
            </li>
          <% end %>
          <li>
            <% if offtaker_signed_in? %>
              <%= link_to "Log out", destroy_offtaker_session_path, method: :delete, data: { "turbo-method": :delete } %>
            <% elsif supplier_signed_in? %>
              <%= link_to "Log out", destroy_supplier_session_path, method: :delete, data: { "turbo-method": :delete } %>
            <% elsif admin_signed_in? %>
              <%= link_to "Log out", destroy_admin_session_path, method: :delete, data: { "turbo-method": :delete } %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
   <div class="bubble-dropdown-wrapper" data-controller="dropdown">
      <button data-action="click->dropdown#handleExpand">
        <span>
          Log in / Sign up
        </span>
        <i class="fas fa-caret-square-down"></i>
      </button>
      <div class="bubble-dropdown collapsed" data-target="dropdown.menu">
        <ul>
          <li>
            <p class="supplier">
              Suppliers
            </p>
          </li>
          <li class="indented">
            <%= link_to "Login", new_supplier_session_path, data: { action: "click->dropdown#close" } %>
          </li>
          <li class="indented">
            <%= link_to "Signup", new_supplier_registration_path, data: { action: "click->dropdown#close" } %>
          </li>
          <li>
            <p class="offtaker">
              Offtakers
            </p>
          </li>
          <li class="indented">
            <%= link_to "Login", new_offtaker_session_path, data: { action: "click->dropdown#close" } %>
          </li>
          <li class="indented">
            <%= link_to "Signup", new_offtaker_registration_path, data: { action: "click->dropdown#close" } %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="footer">
          <svg version="1.1" baseProfile="tiny" id="logo-icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
            x="0px" y="0px" viewBox="0 0 22 29" overflow="visible" xml:space="preserve">
          <path fill="var(--accent-color)" d="M11,27.3c0,0,10-7.8,10-14.9c0-6.1-4.5-11.1-10-11.1S1,6.3,1,12.4C1,19.2,11,27.3,11,27.3z"/>
          <g>
            <path fill="#FFFFFF" d="M12.4,5.4c-0.2-0.6-0.7-1-1.4-1c-0.6,0-1.2,0.4-1.4,1C6.5,6,4.1,8.8,4.1,12.1c0,3.8,3.1,6.9,6.9,6.9
              c3.8,0,6.9-3.1,6.9-6.9C17.9,8.8,15.5,6,12.4,5.4z M11,17.8c-3.1,0-5.7-2.5-5.7-5.7c0-2.7,1.9-5,4.4-5.5C10,7,10.5,7.3,11,7.3
              c0.5,0,1-0.3,1.2-0.7c2.5,0.6,4.4,2.8,4.4,5.5C16.7,15.3,14.1,17.8,11,17.8z"/>
            <ellipse transform="matrix(0.9732 -0.2298 0.2298 0.9732 -2.495 2.854)" fill="#FFFFFF" cx="11" cy="12.1" rx="2.7" ry="2.7"/>
          </g>
          </svg>
          <div class="logos">
            <a href="https://www.niwater.com/home/" target="_blank">
              <%= image_tag 'niw.png' %>
            </a>
            <a href="https://www.kier.co.uk/" target="_blank">
              <%= image_tag 'kier.png' %>
            </a>
            <a href="https://volta-batteries.com/" target="_blank">
            <%= image_tag 'volta.png' %>
            </a>
          </div>


          <ul class="footer-right list-unstyled">
            <li>
              <a href='https://www.mapbox.com/about/maps/' target='_blank'>Maps &copy; Mapbox &copy; OpenStreetMap</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_logo.html.erb
<svg version="1.1" baseProfile="tiny" id="logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	 x="0px" y="0px" viewBox="0 0 151.3 29" overflow="visible" xml:space="preserve">
<path fill="#14274D" d="M39.9,21.9h-3.5v-7.2h-6.6v7.2h-3.5V5.3h3.5v6.5h6.6V5.3h3.5V21.9z"/>
<path fill="#14274D" d="M54.1,21.9H43v-2.4l3.9-4.2c0.5-0.5,0.9-1,1.3-1.5s0.7-0.9,1-1.3c0.3-0.4,0.5-0.9,0.7-1.3
	c0.2-0.4,0.2-0.9,0.2-1.4c0-0.6-0.2-1-0.5-1.3C49.3,8.2,48.8,8,48.3,8c-0.6,0-1.2,0.1-1.7,0.4c-0.6,0.3-1.1,0.7-1.7,1.3l-1.9-2.3
	c0.3-0.3,0.7-0.6,1.1-0.9s0.8-0.5,1.2-0.8c0.4-0.2,0.9-0.4,1.5-0.5c0.5-0.1,1.1-0.2,1.8-0.2c0.8,0,1.5,0.1,2.1,0.3
	c0.6,0.2,1.2,0.5,1.6,0.9s0.8,0.9,1,1.5c0.2,0.6,0.4,1.2,0.4,1.9c0,0.6-0.1,1.3-0.3,1.9s-0.5,1.2-0.9,1.7s-0.8,1.1-1.4,1.7
	s-1.1,1.1-1.7,1.7l-2,2v0.2h6.8V21.9z"/>
<path fill="#14274D" d="M68.3,21.9h-3.5v-7.4c0-0.9-0.2-1.6-0.5-2.1c-0.3-0.5-0.8-0.7-1.6-0.7c-1,0-1.7,0.3-2.1,1
	c-0.4,0.6-0.6,1.7-0.6,3.2v6h-3.5V9.2h2.6l0.5,1.6h0.2c0.4-0.6,0.9-1.1,1.6-1.4C62.2,9.1,63,9,63.8,9c1.5,0,2.6,0.4,3.4,1.2
	c0.8,0.8,1.1,1.9,1.1,3.5V21.9z"/>
<path fill="#14274D" d="M77.6,22.1c-2,0-3.6-0.6-4.8-1.7c-1.1-1.1-1.7-2.7-1.7-4.8c0-2.1,0.5-3.8,1.6-4.9C73.8,9.6,75.2,9,77.1,9
	c1.8,0,3.2,0.5,4.2,1.5c1,1,1.5,2.4,1.5,4.2v1.7h-8.2c0,1,0.3,1.7,0.9,2.3c0.5,0.6,1.3,0.8,2.3,0.8c0.8,0,1.5-0.1,2.2-0.2
	c0.7-0.2,1.4-0.4,2.1-0.8v2.7c-0.6,0.3-1.3,0.5-1.9,0.7C79.5,22,78.6,22.1,77.6,22.1z M77.1,11.4c-0.7,0-1.3,0.2-1.7,0.7
	c-0.4,0.5-0.7,1.1-0.7,2h4.9c0-0.9-0.2-1.5-0.7-2C78.5,11.7,77.9,11.4,77.1,11.4z"/>
<path fill="#14274D" d="M93.7,21.9L93,20.2h-0.1c-0.6,0.7-1.2,1.2-1.8,1.5c-0.6,0.3-1.4,0.4-2.4,0.4c-1.2,0-2.2-0.3-2.9-1
	s-1-1.7-1-3c0-1.3,0.5-2.3,1.4-3c0.9-0.6,2.4-1,4.3-1.1l2.2-0.1v-0.6c0-1.3-0.7-1.9-2-1.9c-1,0-2.2,0.3-3.6,0.9l-1.1-2.3
	C87.4,9.3,89,9,90.8,9c1.7,0,3,0.4,3.9,1.1c0.9,0.7,1.4,1.9,1.4,3.4v8.4H93.7z M92.6,16l-1.3,0c-1,0-1.8,0.2-2.2,0.5
	c-0.5,0.3-0.7,0.8-0.7,1.5c0,1,0.6,1.5,1.7,1.5c0.8,0,1.4-0.2,1.9-0.7c0.5-0.5,0.7-1.1,0.7-1.8V16z"/>
<path fill="#14274D" d="M106.7,9c0.5,0,0.9,0,1.2,0.1l-0.3,3.2c-0.3-0.1-0.6-0.1-1-0.1c-1.1,0-2,0.3-2.6,0.9
	c-0.6,0.6-0.9,1.4-0.9,2.4v6.5h-3.5V9.2h2.6l0.5,2.1h0.2c0.4-0.7,0.9-1.3,1.6-1.7S105.9,9,106.7,9z"/>
<path fill="#D8DDDE" d="M109.7,20.3c0-0.4,0.1-0.7,0.2-0.9c0.1-0.2,0.2-0.4,0.4-0.6c0.2-0.2,0.4-0.3,0.6-0.3s0.5-0.1,0.8-0.1
	c0.3,0,0.5,0,0.8,0.1s0.4,0.2,0.6,0.3c0.2,0.2,0.3,0.3,0.4,0.6c0.1,0.2,0.2,0.5,0.2,0.9c0,0.3-0.1,0.6-0.2,0.9
	c-0.1,0.2-0.2,0.4-0.4,0.6c-0.2,0.2-0.4,0.3-0.6,0.3c-0.2,0.1-0.5,0.1-0.8,0.1c-0.3,0-0.5,0-0.8-0.1c-0.2-0.1-0.5-0.2-0.6-0.3
	c-0.2-0.2-0.3-0.4-0.4-0.6C109.7,20.9,109.7,20.6,109.7,20.3z"/>
<path fill="#14274D" d="M128.1,21.9h-3.5v-7.4c0-0.9-0.2-1.6-0.5-2.1c-0.3-0.5-0.8-0.7-1.4-0.7c-0.9,0-1.5,0.3-1.9,1
	s-0.6,1.7-0.6,3.2v6h-3.5V9.2h2.6l0.5,1.6h0.2c0.3-0.6,0.8-1,1.5-1.4c0.6-0.3,1.4-0.5,2.2-0.5c1.9,0,3.2,0.6,3.9,1.9h0.3
	c0.3-0.6,0.8-1,1.5-1.4s1.4-0.5,2.2-0.5c1.4,0,2.5,0.4,3.3,1.1c0.7,0.7,1.1,1.9,1.1,3.5v8.3h-3.5v-7.4c0-0.9-0.2-1.6-0.5-2.1
	c-0.3-0.5-0.8-0.7-1.4-0.7c-0.8,0-1.5,0.3-1.9,0.9s-0.6,1.6-0.6,2.9V21.9z"/>
<path fill="#14274D" d="M145.3,22.1c-2,0-3.6-0.6-4.8-1.7c-1.1-1.1-1.7-2.7-1.7-4.8c0-2.1,0.5-3.8,1.6-4.9s2.5-1.7,4.4-1.7
	c1.8,0,3.2,0.5,4.2,1.5s1.5,2.4,1.5,4.2v1.7h-8.2c0,1,0.3,1.7,0.9,2.3c0.5,0.6,1.3,0.8,2.3,0.8c0.8,0,1.5-0.1,2.2-0.2
	c0.7-0.2,1.4-0.4,2.1-0.8v2.7c-0.6,0.3-1.3,0.5-1.9,0.7C147.2,22,146.3,22.1,145.3,22.1z M144.8,11.4c-0.7,0-1.3,0.2-1.7,0.7
	c-0.4,0.5-0.7,1.1-0.7,2h4.9c0-0.9-0.2-1.5-0.7-2C146.2,11.7,145.6,11.4,144.8,11.4z"/>
<path fill="var(--accent-color)" d="M11,27.3c0,0,10-7.8,10-14.9c0-6.1-4.5-11.1-10-11.1S1,6.3,1,12.4C1,19.2,11,27.3,11,27.3z"/>
<g>
	<path fill="#FFFFFF" d="M12.4,5.4c-0.2-0.6-0.7-1-1.4-1c-0.6,0-1.2,0.4-1.4,1C6.5,6,4.1,8.8,4.1,12.1c0,3.8,3.1,6.9,6.9,6.9
		c3.8,0,6.9-3.1,6.9-6.9C17.9,8.8,15.5,6,12.4,5.4z M11,17.8c-3.1,0-5.7-2.5-5.7-5.7c0-2.7,1.9-5,4.4-5.5C10,7,10.5,7.3,11,7.3
		c0.5,0,1-0.3,1.2-0.7c2.5,0.6,4.4,2.8,4.4,5.5C16.7,15.3,14.1,17.8,11,17.8z"/>
	<ellipse transform="matrix(0.9732 -0.2298 0.2298 0.9732 -2.495 2.854)" fill="#FFFFFF" cx="11" cy="12.1" rx="2.7" ry="2.7"/>
</g>
</svg>

app/views/shared/_navbar.html.erb
<div class="navbar-h2-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="navbar-h2">
          <%= link_to root_path do %>
            <%= render partial: 'shared/logo' %>
          <% end %>
          <div class="navbar-right">
            <%= render partial: "shared/dropdown" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>