config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: { 
    registrations: "suppliers/registrations",
    sessions: "suppliers/sessions"
   }
  devise_for :offtakers, controllers: { 
    registrations: "offtakers/registrations",
    sessions: "offtakers/sessions"
   }
   devise_for :admins, controllers: { 
    registrations: "admin/registrations",
    sessions: "admin/sessions"
   }, path: 'admin'

  authenticate :admin, ->(admin) { admin } do
    namespace :admin do
      get '/', to: 'supplier_locations#index'
      post '/supplier_locations/:id/verify', as: :verify, to: "supplier_locations#verify"
    end
  end

  namespace :api do
    namespace :v1 do
      # Offtaker location creation
      get '/charts/offtaker_location_weekly', 
      to: 'charts#offtaker_location_weekly', 
      as: 'charts_offtaker_location_weekly'

      get '/charts/offtaker_location_monthly', 
      to: 'charts#offtaker_location_monthly', 
      as: 'charts_offtaker_location_monthly'

      get '/charts/offtaker_location_yearly', 
      to: 'charts#offtaker_location_yearly', 
      as: 'charts_offtaker_location_yearly'  

      # Offtaker location by volume requested
      get '/charts/offtaker_location_volume_weekly', 
      to: 'charts#offtaker_location_volume_weekly', 
      as: 'charts_offtaker_location_volume_weekly'

      get '/charts/offtaker_location_volume_monthly', 
      to: 'charts#offtaker_location_volume_monthly', 
      as: 'charts_offtaker_location_volume_monthly'

      get '/charts/offtaker_location_volume_yearly', 
      to: 'charts#offtaker_location_volume_yearly', 
      as: 'charts_offtaker_location_volume_yearly'  

      # Offtaker location by oxygen_interest requested
      get '/charts/offtaker_location_oxygen_interest_weekly', 
      to: 'charts#offtaker_location_oxygen_interest_weekly', 
      as: 'charts_offtaker_location_oxygen_interest_weekly'

      get '/charts/offtaker_location_oxygen_interest_monthly', 
      to: 'charts#offtaker_location_oxygen_interest_monthly', 
      as: 'charts_offtaker_location_oxygen_interest_monthly'

      get '/charts/offtaker_location_oxygen_interest_yearly', 
      to: 'charts#offtaker_location_oxygen_interest_yearly', 
      as: 'charts_offtaker_location_oxygen_interest_yearly'  

      # Scenario creation
      get '/charts/scenario_weekly', 
      to: 'charts#scenario_weekly', 
      as: 'charts_scenario_weekly'

      get '/charts/scenario_monthly', 
      to: 'charts#scenario_monthly', 
      as: 'charts_scenario_monthly'

      get '/charts/scenario_yearly', 
      to: 'charts#scenario_yearly', 
      as: 'charts_scenario_yearly'  

      # Average road costs
      get '/charts/average_road_costs_weekly', 
      to: 'charts#average_road_costs_weekly', 
      as: 'charts_average_road_costs_weekly'

      get '/charts/average_road_costs_monthly', 
      to: 'charts#average_road_costs_monthly', 
      as: 'charts_average_road_costs_monthly'

      get '/charts/average_road_costs_yearly', 
      to: 'charts#average_road_costs_yearly', 
      as: 'charts_average_road_costs_yearly'  

      # Average distance
      get '/charts/average_distance_weekly', 
      to: 'charts#average_distance_weekly', 
      as: 'charts_average_distance_weekly'

      get '/charts/average_distance_monthly', 
      to: 'charts#average_distance_monthly', 
      as: 'charts_average_distance_monthly'

      get '/charts/average_distance_yearly', 
      to: 'charts#average_distance_yearly', 
      as: 'charts_average_distance_yearly'  

      # Average pipeline costs
      get '/charts/average_pipeline_costs_weekly', 
      to: 'charts#average_pipeline_costs_weekly', 
      as: 'charts_average_pipeline_costs_weekly'

      get '/charts/average_pipeline_costs_monthly', 
      to: 'charts#average_pipeline_costs_monthly', 
      as: 'charts_average_pipeline_costs_monthly'

      get '/charts/average_pipeline_costs_yearly', 
      to: 'charts#average_pipeline_costs_yearly', 
      as: 'charts_average_pipeline_costs_yearly'  

      # Offtaker creation
      get '/charts/offtaker_weekly', 
      to: 'charts#offtaker_weekly', 
      as: 'charts_offtaker_weekly'

      get '/charts/offtaker_monthly', 
      to: 'charts#offtaker_monthly', 
      as: 'charts_offtaker_monthly'

      get '/charts/offtaker_yearly', 
      to: 'charts#offtaker_yearly', 
      as: 'charts_offtaker_yearly'  

      # Offtaker scenarios created
      get '/charts/offtaker_scenarios_created_weekly', 
      to: 'charts#offtaker_scenarios_created_weekly', 
      as: 'charts_offtaker_scenarios_created_weekly'

      get '/charts/offtaker_scenarios_created_monthly', 
      to: 'charts#offtaker_scenarios_created_monthly', 
      as: 'charts_offtaker_scenarios_created_monthly'

      get '/charts/offtaker_scenarios_created_yearly', 
      to: 'charts#offtaker_scenarios_created_yearly', 
      as: 'charts_offtaker_scenarios_created_yearly'  
    end
  end

  resources :scenarios, only: [:create, :show, :destroy]
  post '/scenarios/:id/mark-favourite', as: :mark_favourite, to: "scenarios#mark_favourite"
  post '/scenarios/:id/calculate-again', as: :calculate_again, to: "scenarios#calculate_again"


  namespace :suppliers, suppliers: true do 
    get '/', to: 'supplier_locations#dashboard'
    get '/filter', to: 'supplier_locations#filter', as: :filter
    resources :supplier_locations, except: [:index]
  end

  namespace :offtakers, offtakers: true do 
    get '/', to: 'offtaker_locations#dashboard'
    resources :offtaker_locations, except: [:index]
  end

  root 'pages#home'
  get '/about', to: "pages#about"
  get '/terms_and_conditions', to: "pages#terms_and_conditions"
  get '/privacy_statement', to: "pages#privacy_statement"

end

app/views/pages/about.html.erb
<% content_for :title, "About us" %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>
        About us page
      </h1>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :title, "Home" %>

<div class="banner-wrapper" data-controller="maps">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 order-2 order-md-1">
        <div class="banner">
          <div class="banner-content">
            <h1>
              Find out how close you are to hydrogen
            </h1>
            <p>
              Try out our calculator and find out:
            </p>
            <ul>
              <li>
                How far you are from suppliers
              </li>
              <li>
                The approximate cost of transport by road, dedicated pipeline or import
              </li>
              <li>
                Availability of volume in your region
              </li>
            </ul>
              
            <% if current_offtaker %>
              <%= link_to offtakers_path, class: 'btn btn-primary btn-inverted' do %>
                Go to your dashboard &rarr;
              <% end %>
            <% elsif current_supplier %>
              <%= link_to suppliers_path, class: 'btn btn-primary btn-inverted' do %>
                Go to your dashboard &rarr;
              <% end %>
            <% elsif current_admin %>
              <%= link_to admin_path, class: 'btn btn-primary btn-inverted' do %>
                Go to your dashboard &rarr;
              <% end %>
            <% else %>
              <p>
                <%= link_to new_offtakers_offtaker_location_path, class: 'btn btn-primary btn-inverted' do %>
                  Enter your information &rarr;
                <% end %>
              </p>
              <%= link_to "Or sign up as a supplier", new_supplier_registration_path, class: "text-light" %>
            <% end %>

          </div>

        </div>
      </div>
      <div class="col-12 col-md-6 order-1 order-md-2">
        <div id="map" class="uninteractable" data-maps-target="map" data-key="<%= ENV['MAPBOX_API_KEY'] %>" data-center="<%= [-6.599110, 54.607009].to_json %>" data-zoom="8" data-locations="<%= @supplier_locations.map {|supplier_location| [supplier_location.longitude, supplier_location.latitude] }.to_json %>"></div>
        <div class="map-padding"></div>
      </div>
    </div>
  </div>
</div>

app/views/pages/privacy_statement.html.erb
<% content_for :title, "Privacy statement" %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>
        Privacy statement
      </h1>
    </div>
  </div>
</div>

app/views/pages/terms_and_conditions.html.erb
<% content_for :title, "Terms and conditions" %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>
        Terms and conditions
      </h1>
    </div>
  </div>
</div>