config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: { 
    registrations: "suppliers/registrations",
    sessions: "suppliers/sessions"
   }
  devise_for :offtakers, controllers: { 
    registrations: "offtakers/registrations",
    sessions: "offtakers/sessions"
   }
   devise_for :admins, controllers: { 
    registrations: "admin/registrations",
    sessions: "admin/sessions"
   }, path: 'admin'

  authenticate :admin, ->(admin) { admin } do
    namespace :admin do
      get '/', to: 'supplier_locations#index'
      post '/supplier_locations/:id/verify', as: :verify, to: "supplier_locations#verify"
    end
  end

  namespace :api do
    namespace :v1 do
      # Offtaker location creation
      get '/charts/offtaker_location_weekly', 
      to: 'charts#offtaker_location_weekly', 
      as: 'charts_offtaker_location_weekly'

      get '/charts/offtaker_location_monthly', 
      to: 'charts#offtaker_location_monthly', 
      as: 'charts_offtaker_location_monthly'

      get '/charts/offtaker_location_yearly', 
      to: 'charts#offtaker_location_yearly', 
      as: 'charts_offtaker_location_yearly'  

      # Offtaker location by volume requested
      get '/charts/offtaker_location_volume_weekly', 
      to: 'charts#offtaker_location_volume_weekly', 
      as: 'charts_offtaker_location_volume_weekly'

      get '/charts/offtaker_location_volume_monthly', 
      to: 'charts#offtaker_location_volume_monthly', 
      as: 'charts_offtaker_location_volume_monthly'

      get '/charts/offtaker_location_volume_yearly', 
      to: 'charts#offtaker_location_volume_yearly', 
      as: 'charts_offtaker_location_volume_yearly'  

      # Offtaker location by oxygen_interest requested
      get '/charts/offtaker_location_oxygen_interest_weekly', 
      to: 'charts#offtaker_location_oxygen_interest_weekly', 
      as: 'charts_offtaker_location_oxygen_interest_weekly'

      get '/charts/offtaker_location_oxygen_interest_monthly', 
      to: 'charts#offtaker_location_oxygen_interest_monthly', 
      as: 'charts_offtaker_location_oxygen_interest_monthly'

      get '/charts/offtaker_location_oxygen_interest_yearly', 
      to: 'charts#offtaker_location_oxygen_interest_yearly', 
      as: 'charts_offtaker_location_oxygen_interest_yearly'  

      # Scenario creation
      get '/charts/scenario_weekly', 
      to: 'charts#scenario_weekly', 
      as: 'charts_scenario_weekly'

      get '/charts/scenario_monthly', 
      to: 'charts#scenario_monthly', 
      as: 'charts_scenario_monthly'

      get '/charts/scenario_yearly', 
      to: 'charts#scenario_yearly', 
      as: 'charts_scenario_yearly'  

      # Average road costs
      get '/charts/average_road_costs_weekly', 
      to: 'charts#average_road_costs_weekly', 
      as: 'charts_average_road_costs_weekly'

      get '/charts/average_road_costs_monthly', 
      to: 'charts#average_road_costs_monthly', 
      as: 'charts_average_road_costs_monthly'

      get '/charts/average_road_costs_yearly', 
      to: 'charts#average_road_costs_yearly', 
      as: 'charts_average_road_costs_yearly'  

      # Average distance
      get '/charts/average_distance_weekly', 
      to: 'charts#average_distance_weekly', 
      as: 'charts_average_distance_weekly'

      get '/charts/average_distance_monthly', 
      to: 'charts#average_distance_monthly', 
      as: 'charts_average_distance_monthly'

      get '/charts/average_distance_yearly', 
      to: 'charts#average_distance_yearly', 
      as: 'charts_average_distance_yearly'  

      # Average pipeline costs
      get '/charts/average_pipeline_costs_weekly', 
      to: 'charts#average_pipeline_costs_weekly', 
      as: 'charts_average_pipeline_costs_weekly'

      get '/charts/average_pipeline_costs_monthly', 
      to: 'charts#average_pipeline_costs_monthly', 
      as: 'charts_average_pipeline_costs_monthly'

      get '/charts/average_pipeline_costs_yearly', 
      to: 'charts#average_pipeline_costs_yearly', 
      as: 'charts_average_pipeline_costs_yearly'  

      # Offtaker creation
      get '/charts/offtaker_weekly', 
      to: 'charts#offtaker_weekly', 
      as: 'charts_offtaker_weekly'

      get '/charts/offtaker_monthly', 
      to: 'charts#offtaker_monthly', 
      as: 'charts_offtaker_monthly'

      get '/charts/offtaker_yearly', 
      to: 'charts#offtaker_yearly', 
      as: 'charts_offtaker_yearly'  

      # Offtaker scenarios created
      get '/charts/offtaker_scenarios_created_weekly', 
      to: 'charts#offtaker_scenarios_created_weekly', 
      as: 'charts_offtaker_scenarios_created_weekly'

      get '/charts/offtaker_scenarios_created_monthly', 
      to: 'charts#offtaker_scenarios_created_monthly', 
      as: 'charts_offtaker_scenarios_created_monthly'

      get '/charts/offtaker_scenarios_created_yearly', 
      to: 'charts#offtaker_scenarios_created_yearly', 
      as: 'charts_offtaker_scenarios_created_yearly'  
    end
  end

  resources :scenarios, only: [:create, :show, :destroy]
  post '/scenarios/:id/mark-favourite', as: :mark_favourite, to: "scenarios#mark_favourite"
  post '/scenarios/:id/calculate-again', as: :calculate_again, to: "scenarios#calculate_again"


  namespace :suppliers, suppliers: true do 
    get '/', to: 'supplier_locations#dashboard'
    get '/filter', to: 'supplier_locations#filter', as: :filter
    resources :supplier_locations, except: [:index]
  end

  namespace :offtakers, offtakers: true do 
    get '/', to: 'offtaker_locations#dashboard'
    resources :offtaker_locations, except: [:index]
  end

  root 'pages#home'
  get '/about', to: "pages#about"
  get '/terms_and_conditions', to: "pages#terms_and_conditions"
  get '/privacy_statement', to: "pages#privacy_statement"

end

app/models/scenario.rb
class Scenario < ApplicationRecord
  include Hashid::Rails

  before_save :run_calculations

  belongs_to :offtaker_location
  belongs_to :supplier_location
  
  validates :distance, presence: true

  def present
    ScenarioPresenter.new(self)
  end

  def run_calculations
    attributes = CostCalculationService.new(self).call
    self.assign_attributes(attributes)
  end

  def compare_cheapest_h2(value)
    if value == self.costs_road
      return 'road'
    elsif value == self.costs_pipeline
      return 'pipeline'
    elsif value == self.costs_import
      return 'import'
    end
  end

  def self.compose_chart_data_weekly(start_date)
    past_week_dates = (start_date..(start_date + 6.days).to_date).map{ |date| date }
    past_week_scenarios = Scenario.where(created_at: (start_date..(start_date + 6.days).to_date))
    formatted_dates = past_week_dates.map do |date|
      scenarios = past_week_scenarios.select {|scenario| scenario.created_at.to_date == date }
      [date.strftime("%a"), (scenarios.inject(0) do |sum, scenario|
        sum += yield(scenario)
      end)]
    end
    return formatted_dates
  end

  def self.compose_chart_data_monthly(start_date)
    week_numbers_this_month = (start_date.beginning_of_month.to_date..start_date.end_of_month.to_date).uniq {|date| date.strftime("%U")}.map {|date| date.strftime("%U").to_i}
    past_month_scenarios = Scenario.where(created_at: (start_date.beginning_of_month.to_date..start_date.end_of_month.to_date))
    grouped_by_weeknumber = past_month_scenarios.group_by {|scenario| scenario.created_at.strftime("%U").to_i }

    formatted_weeks = grouped_by_weeknumber.map {|week_number, scenarios| [week_number, (scenarios.inject(0) do |sum, scenario|
      sum += yield(scenario)
    end)]}
    padded_weeks = week_numbers_this_month.map do |number| 
      week_with_data = formatted_weeks.find {|week_number, sum| number == week_number }
      ["Week #{number} | #{start_date.strftime("%b")}", (week_with_data ? week_with_data[1].round(2) : 0)]
    end
    return padded_weeks
  end

  def self.compose_chart_data_yearly(start_date)
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    past_year_scenarios = Scenario.where(created_at: (start_date.beginning_of_year.to_date..start_date.end_of_year.to_date))
    grouped_by_month = past_year_scenarios.group_by {|scenario| scenario.created_at.strftime("%b") }
    formatted_months = grouped_by_month.map {|month, scenarios| [month, (scenarios.inject(0) do |sum, scenario|
      sum += yield(scenario)
    end)]}
    padded_months = months.map do |month| 
      month_with_data = formatted_months.find {|month_name, sum| month == month_name }
      [month, (month_with_data ? month_with_data[1].round(2) : 0)]
    end
    return padded_months
  end

  def self.set_history_for_chart_creation(start_date, variant)
    case variant
    when 'weekly'
      compose_chart_data_weekly(start_date) do |scenario|
        1
      end
    when 'monthly'
      compose_chart_data_monthly(start_date) do |scenario|
        1
      end
    when 'yearly'
      compose_chart_data_yearly(start_date) do |scenario|
        1
      end
    end
  end
  
  def self.set_history_for_chart_average_road_cost(start_date, variant)
    case variant
    when 'weekly'
      compose_chart_data_weekly(start_date) do |scenario|
        (scenario.costs_road || 0)
      end
    when 'monthly'
      compose_chart_data_monthly(start_date) do |scenario|
        (scenario.costs_road || 0)
      end
    when 'yearly'
      compose_chart_data_yearly(start_date) do |scenario|
        (scenario.costs_road || 0)
      end
    end
  end
  
  def self.set_history_for_chart_average_distance(start_date, variant)
    case variant
    when 'weekly'
      compose_chart_data_weekly(start_date) do |scenario|
        (scenario.distance || 0)
      end
    when 'monthly'
      compose_chart_data_monthly(start_date) do |scenario|
        (scenario.distance || 0)
      end
    when 'yearly'
      compose_chart_data_yearly(start_date) do |scenario|
        (scenario.distance || 0)
      end
    end
  end

  def self.set_history_for_chart_average_pipeline_cost(start_date, variant)
    case variant
    when 'weekly'
      compose_chart_data_weekly(start_date) do |scenario|
        (scenario.costs_pipeline || 0)
      end
    when 'monthly'
      compose_chart_data_monthly(start_date) do |scenario|
        (scenario.costs_pipeline || 0)
      end
    when 'yearly'
      compose_chart_data_yearly(start_date) do |scenario|
        (scenario.costs_pipeline || 0)
      end
    end
  end

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  include Rails.application.routes.url_helpers
  before_action :set_scenario, only: [:show, :destroy, :mark_favourite, :calculate_again]

  def create
    session.delete(:first_visit)
    is_new_record = false
    @scenario = Scenario.find_by(
      supplier_location_id: params[:scenario][:supplier_location_id],
      offtaker_location_id: params[:scenario][:offtaker_location_id]
    )
    
    unless @scenario
      is_new_record = true
      @scenario = Scenario.new(scenario_params)
    end
    @scenario.distance = params["scenario"]["distance"]
    @scenario.save!
    
    respond_to do |format|
      format.json {
          render json: {
              scenario: @scenario,
              scenario_url: scenario_url(@scenario),
              scenario_html: scenario_response(is_new_record), 
          }
      }
    end
  end

  def show
    if @scenario.costs_pipeline.nil? || 
       @scenario.costs_road.nil?
        @scenario.run_calculations
    end
    @cheapest = [@scenario.costs_road, @scenario.costs_pipeline, @scenario.costs_import].min
  end

  def destroy
    @scenario.destroy
    if current_offtaker
      redirect_to offtakers_path
    elsif current_supplier
      redirect_to suppliers_path
    end
  end

  def mark_favourite
    @scenario.favourite = !@scenario.favourite
    @scenario.save
    respond_to do |format|
      format.js
      format.json {
        render json: {
            scenario: @scenario,
        }
    }
    end
  end

  def calculate_again
    @scenario.run_calculations
    @scenario.save
    redirect_to scenario_path(@scenario)
  end

  private

  def set_scenario
    @scenario = Scenario.find(params[:id])
  end

  def scenario_response(is_new_record)
    if is_new_record
      render_to_string(
        partial: "scenarios/scenario", 
        formats: [:html], 
        locals: { 
          scenario: @scenario 
          }
        )
    else
      ""
    end
  end

  def scenario_params
    params.require(:scenario).permit(:distance, :supplier_location_id, :offtaker_location_id)
  end
end

app/views/scenarios/_breakdown.html.erb
<% if @scenario.value_breakdown %>
<% value_breakdown = JSON.parse(@scenario.value_breakdown) %>

<div class="breakdown">
  Pipeline
  <div class="stacked-bar-chart">
    <div style="width:<%= pipeline_breakdown(value_breakdown)[:production_percent] %>%;" aria-label="Production: <%= pipeline_breakdown(value_breakdown)[:production] %>" data-balloon-pos="up"></div>
    <div style="width:<%= pipeline_breakdown(value_breakdown)[:compression_percent] %>%;" aria-label="Compression: <%= pipeline_breakdown(value_breakdown)[:compression] %>" data-balloon-pos="up"></div>
    <div style="width:<%= pipeline_breakdown(value_breakdown)[:purification_percent] %>%;" aria-label="Purification: <%= pipeline_breakdown(value_breakdown)[:purification] %>" data-balloon-pos="up"></div>
    <div style="width:<%= pipeline_breakdown(value_breakdown)[:transport_percent] %>%;" aria-label="Transport: <%= pipeline_breakdown(value_breakdown)[:transport] %>" data-balloon-pos="up"></div>
  </div>
  <ul class="stacked-bar-chart-legend">
    <li>
      <div class="orb"></div>
      Production: £
      <%= pipeline_breakdown(value_breakdown)[:production]  %>
    </li>
    <li>
      <div class="orb"></div>
      Compression: £
      <%= pipeline_breakdown(value_breakdown)[:compression]  %>
    </li>
    <li>
      <div class="orb"></div>
      Purification: £
      <%= pipeline_breakdown(value_breakdown)[:purification]  %>
    </li>
    <li>
      <div class="orb"></div>
      Transport: £
      <%= pipeline_breakdown(value_breakdown)[:transport]  %>
    </li>
  </ul>
  Road
  <div class="stacked-bar-chart">
    <div style="width:<%= road_breakdown(value_breakdown)[:production_percent] %>%;" aria-label="Production: <%= road_breakdown(value_breakdown)[:production] %>" data-balloon-pos="up"></div>
    <div style="width:<%= road_breakdown(value_breakdown)[:compression_percent] %>%;" aria-label="Compression: <%= road_breakdown(value_breakdown)[:compression] %>" data-balloon-pos="up"></div>
    <div style="width:<%= road_breakdown(value_breakdown)[:purification_percent] %>%;" aria-label="Purification: <%= road_breakdown(value_breakdown)[:purification] %>" data-balloon-pos="up"></div>
    <div style="width:<%= road_breakdown(value_breakdown)[:transport_percent] %>%;" aria-label="Transport: <%= road_breakdown(value_breakdown)[:transport] %>" data-balloon-pos="up"></div>
  </div>
  <ul class="stacked-bar-chart-legend">
    <li>
      <div class="orb"></div>
      Production: £
      <%= road_breakdown(value_breakdown)[:production]  %>
    </li>
    <li>
      <div class="orb"></div>
      <p class="m-0">
        Compression: £
        <%= road_breakdown(value_breakdown)[:compression]  %>
        <span data-balloon-pos="up" aria-label="Compression is not relevant for pipeline cost breakdown">
          <i class="fa-solid fa-circle-question"></i>
        </span>
      </p>
    </li>
    <li>
      <div class="orb"></div>
      Purification: £
      <%= road_breakdown(value_breakdown)[:purification]  %>
    </li>
    <li>
      <div class="orb"></div>
      Transport: £
      <%= road_breakdown(value_breakdown)[:transport]  %>
    </li>
  </ul>
</div>
<% end %> 

app/views/scenarios/_scenario.html.erb
  <li id="<%= dom_id scenario %>">
    <%= link_to scenario_path(scenario) do %>
      View scenario report: <%= "#{offtaker_signed_in? ? scenario.supplier_location.name : scenario.offtaker_location.name} - #{scenario.distance}km" %> &rarr;
    <% end %>
    <button 
      data-action="click->maps#drawRoute" 
      data-location="<%= offtaker_signed_in? ? [scenario.supplier_location.longitude, scenario.supplier_location.latitude, (scenario.supplier_location.name || scenario.supplier_location.address), scenario.supplier_location.id].to_json : [scenario.offtaker_location.longitude, scenario.offtaker_location.latitude, (scenario.offtaker_location.name || scenario.offtaker_location.address), scenario.offtaker_location.id].to_json %>"
      class="btn btn-primary"
      aria-label="Show on map" 
      data-balloon-pos="up"
    >
      <i class="fa-solid fa-route"></i>
    </button>
  </li>

app/views/scenarios/show.html.erb
<% content_for :title, "Scenario details for #{@scenario.offtaker_location.name} to #{@scenario.supplier_location.name}" %>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 pb-4 order-2 order-md-1">
      <%= link_to back_link, class: "back-button" do %>
        &larr; Back to dashboard
      <% end %>
      <h1>
        Scenario details for '<%= offtaker_signed_in? ? @scenario.offtaker_location.name : @scenario.supplier_location.name %>' to '<%= offtaker_signed_in? ? @scenario.supplier_location.name : @scenario.offtaker_location.name %>''
      </h1>
      <div class="buttons my-3">    
        <%= link_to scenario_path(@scenario), method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this scenario?" }, class: "btn btn-danger"  do %>
          <i class="fa-solid fa-trash-can"></i>
        <% end %>
        <%= button_to calculate_again_path(@scenario), 
              method: :post, 
              'aria-label': "Re-run calculations", 
              class: "btn btn-info",
              form_class: "d-inline-block",
              data: { 
                'balloon-pos': 'up' 
                } do %>
          <i class="fa-solid fa-retweet"></i>
        <% end %>
        <% if offtaker_signed_in? %>
          <button
          data-controller="mark-favourite" data-action="click->mark-favourite#handleClick"
          data-url="<%= mark_favourite_url(@scenario) %>"
          class="rating-button btn <%= 'active' if @scenario.favourite %>">
            <i class="fa-solid fa-star"></i> 
          </button>
        <% elsif supplier_signed_in? %>
          <button
          aria-label="<%= @scenario.favourite ? 'Offtaker has favourited this scenario' : 'Scenario has not been favourited' %>" data-balloon-pos="up"
          class="rating-button btn <%= 'active' if @scenario.favourite %>">
            <i class="fa-solid fa-star"></i> 
          </button>
        <% end %>
      </div>

      <ul class="nav nav-pills" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="scenario-tab" data-bs-toggle="tab" data-bs-target="#scenario" type="button" role="tab" aria-controls="scenario" aria-selected="true">
            Scenario
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="breakdown-tab" data-bs-toggle="tab" data-bs-target="#breakdown" type="button" role="tab" aria-controls="breakdown" aria-selected="false">
            Cost breakdown
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="offtaker-tab" data-bs-toggle="tab" data-bs-target="#offtaker" type="button" role="tab" aria-controls="offtaker" aria-selected="false">
            Offtaker location
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="supplier-tab" data-bs-toggle="tab" data-bs-target="#supplier" type="button" role="tab" aria-controls="supplier" aria-selected="false">
            Supplier location
          </button>
        </li>
      </ul>

      <div class="tab-content my-4" id="myTabContent">
        <div class="tab-pane show active pb-4" id="scenario" role="tabpanel" aria-labelledby="scenario-tab">
          <div class="alert alert-info mt-3" role="alert">
            Dislaimer: All data displayed should be considered indicative, no rights can be derived from calculations performed on this platform. 
          </div>
          <div class="data">
            <div class="data-label">
              Offtaker location: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.offtaker_location.name || @scenario.offtaker_location.address %>">
              <%= @scenario.offtaker_location.name || @scenario.offtaker_location.address %>
            </div>
            <div class="data-label">
              Supplier location: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.supplier_location.name || @scenario.supplier_location.address %>">
              <%= @scenario.supplier_location.name || @scenario.supplier_location.address %>
            </div>
            <div class="data-label">
              Distance: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.distance %>">
              <%= @scenario.present.distance %>
              <a data-bs-toggle="collapse" href="#collapse-distance" role="button" aria-expanded="false" aria-controls="collapse-distance">
                <i class="fa-solid fa-circle-question"></i>
              </a>
            </div>
            <div class="collapse mt-2 data-row" id="collapse-distance">
              <div class="card card-body">
                This is the distance calculated following road networks, the other distance displayed is calculated 'as the crow flies'.
              </div>
            </div>
            <div class="data-label">
              Distance straight line: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.distance_straight_line %>">
              <%= @scenario.present.distance_straight_line %>
              <a data-bs-toggle="collapse" href="#collapse-straight-line" role="button" aria-expanded="false" aria-controls="collapse-straight-line">
                <i class="fa-solid fa-circle-question"></i>
              </a>
            </div>
            <div class="collapse mt-2 data-row" id="collapse-straight-line">
              <div class="card card-body">
                This is the distance 'as the crow flies', the other distance shown is the calculated distance following road networks.
              </div>
            </div>
            <div class="data-label">
              Costs Road H2: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.costs_road %>">
              <%= @scenario.present.costs_road %> <span class="text-secondary data-unit">/ day</span>
            </div>
            <div class="data-label">
              Costs Pipeline H2: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.costs_pipeline %>">
              <%= @scenario.present.costs_pipeline %> <span class="text-secondary data-unit">/ day</span>
              <a data-bs-toggle="collapse" href="#collapse-cost-pipeline" role="button" aria-expanded="false" aria-controls="collapse-cost-pipeline">
                <i class="fa-solid fa-circle-question"></i>
              </a>
            </div>
            <div class="collapse mt-2 data-row" id="collapse-cost-pipeline">
              <div class="card card-body">
                <p class="m-0">
                  This is the approximate cost calculated for building a pipeline, per day, based on values provided by both the supplier location and the offtaker location.
                  <br>
                  This indication of costs follows the distance between locations by <strong>road networks</strong>
                </p>
              </div>
            </div>
            <div class="data-label">
              Costs Pipeline H2 straight line: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.costs_pipeline_straight_line %>">
              <%= @scenario.present.costs_pipeline_straight_line %> <span class="text-secondary data-unit">/ day</span>
              <a data-bs-toggle="collapse" href="#collapse-cost-straight-line" role="button" aria-expanded="false" aria-controls="collapse-cost-straight-line">
                <i class="fa-solid fa-circle-question"></i>
              </a>
            </div>
            <div class="collapse mt-2 data-row" id="collapse-cost-straight-line">
              <div class="card card-body">
                <p class="m-0">
                  This is the approximate cost calculated for building a pipeline, per day, based on values provided by both the supplier location and the offtaker location.
                  <br>
                  This indication of costs follows the distance between locations <strong>as the crow flies, in a straight line</strong>.
                </p>
              </div>
            </div>
            <div class="data-label">
              Required Offtaker H2: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.present.required_hydrogen_volume? %>">
              <%= @scenario.present.required_hydrogen_volume %> <span class="text-secondary data-unit">/ day</span>
            </div>
            <div class="data-label">
              Costs import H2: 
            </div>
            <div class="data-value <%= 'empty' unless @scenario.costs_import %>">
              <%= @scenario.present.costs_import %> <span class="text-secondary data-unit">/ day</span>
            </div>
            <div class="data-label">
              Cheapest option H2: 
            </div>
            <div class="data-value <%= 'empty' unless @cheapest %>">
              <p>
                <%= @scenario.present.cheapest_option(@cheapest) %> <span class="text-secondary data-unit">/ day</span>
              </p>
            </div>
          </div>
        </div>
        <div class="tab-pane pb-4" id="breakdown" role="tabpanel" aria-labelledby="breakdown-tab">
          <h2 class="mt-4">
            Breakdown per day
          </h2>
          <%= render partial: "breakdown", locals: { scenario: @scenario } %>
        </div>
        <div class="tab-pane pb-4" id="offtaker" role="tabpanel" aria-labelledby="offtaker-tab">
          <%= render partial: "offtakers/offtaker_locations/offtaker_location_details", locals: { offtaker_location: @scenario.offtaker_location } %>
        </div>
        <div class="tab-pane pb-4" id="supplier" role="tabpanel" aria-labelledby="supplier-tab">
          <%= render partial: "suppliers/supplier_locations/supplier_location_details", locals: { supplier_location: @scenario.supplier_location } %>
          <div class="data-wrapper data-list">
            <h4 class="my-3">
              Supply details by purity
            </h4>

            <div class="accordion my-3" id="supply-types-accordion">
              <% @scenario.supplier_location.supply_types.each_with_index do |supply_type, index| %>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="<%= supply_type.id %>">
                    <button class="accordion-button <%= 'collapsed' unless supply_type.name === @scenario.offtaker_location.required_hydrogen_purity %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= supply_type.id %>" aria-expanded="true" aria-controls="collapse-<%= supply_type.id %>">
                      <%= supply_type.name %>
                    </button>
                  </h2>
                  <div id="collapse-<%= supply_type.id %>" class="accordion-collapse collapse <%= 'show' if supply_type.name === @scenario.offtaker_location.required_hydrogen_purity %>" aria-labelledby="<%= supply_type.id %>" data-bs-parent="#supply-types-accordion">
                    <div class="accordion-body light-wrapper pb-5">
                      <%= render partial: "suppliers/supplier_locations/supply_type_details", locals: { supply_type: supply_type } %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>

          </div>
        </div>
      </div>

    <% if offtaker_signed_in? %>
      <%= link_to offtakers_offtaker_location_path(@scenario.offtaker_location), class: "btn btn-primary" do %>
        Explore other locations &rarr;
      <% end %>
    <% end %>

    </div>
    <div class="col-12 col-md-6 order-1 order-md-2">
      <div data-controller="route" class="h-100 position-relative">
        <div id="routing-results"></div>

        <div 
          id="map" 
          class="sticky"
          data-route-target="map" 
          data-key="<%= ENV['MAPBOX_API_KEY'] %>" 
          data-center="<%= [@scenario.offtaker_location.longitude, @scenario.offtaker_location.latitude].to_json %>" 
          data-zoom="9" 
          data-origin="<%= [@scenario.offtaker_location.longitude, @scenario.offtaker_location.latitude, (@scenario.offtaker_location.name || @scenario.offtaker_location.address), @scenario.offtaker_location.id].to_json %>" 
          data-destination="<%= [@scenario.supplier_location.longitude, @scenario.supplier_location.latitude, (@scenario.supplier_location.name || @scenario.supplier_location.address), @scenario.supplier_location.id].to_json %>"
        >
        </div>
        <div class="map-padding"></div>
      </div>
    </div>
  </div>
</div>